services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      SERVER_ENV: ${SERVER_ENV}
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
  simulation:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 400M

volumes:
  app-db:
    external: true